### ISSUE TITLE
getWeatherFeature() - Deprecated

### ISSUE THREAD

**Issue by dantonino** [stelpro/maestro-thermostat#1]
Hi,

Since January 1, 2019, [this API is removed](https://docs.smartthings.com/en/latest/ref-docs/smartapp-ref.html?highlight=getWeatherFeature#getweatherfeature-deprecated). We should use  getTwcConditions(), getTwcForecast(), getTwcAlerts(), getTwcLocation(), or getTwcAlertDetail() for alternative weather APIs.

Thanks!
Diego

**Comment by stelpro** [comment]
Hi Diego,

Yes, you are right.
However, Stelpro will soon obsolete its device handlers since we are near the official Work With SmartThings certification.
That means that you will no longer need to use this device handler and instead use the device handler officially supported by SmartThings for the Stelpro devices.

**Comment by dantonino** [comment]
This are great news! Do you have any ETA on that? Looking forward for this.
Diego

**Comment by stelpro** [comment]
The device handlers are already available on the SmartThings platform, but they are still in QA phase.

**Comment by vincentbarge** [comment]
Hi Stelpro, do you know if the device handler will handle power consumption?

**Comment by stelpro** [comment]
No, power consumption will not be handled by the device handler

**Comment by vincentbarge** [comment]
When I both mines that was especially because off this feature that was not handled by the ZWave one.
Sad to see that now even on your website Stelpro removed this feature. I have the feeling that I've been fooled.

**Comment by stelpro** [comment]
Stelpro Maestro thermostats have a power consumption feature.
But they must be used with the Stelpro Maestro thermostat controller in order to take advantage of it.
Stelpro offers compatibility with SmartThings and other hubs, but it's not all features that are supported with them.

**Comment by vincentbarge** [comment]
Stelpro is not the only one being able to optimize power consumption... I've many devices that have the power consumption feature and I do take advantage of them using my own logics (thanks WebCore), and to integrate all of them together.
Here is a simple example of why you should provide at least the power consumption (read). Get statistic of were you consumption go within your home. This is call having an integrated house. Not providing the power consumption outside of your devices is basically the opposite of what users like about open source smart home.
Can I have a refund on my thermostats, as it seems Stelpro removed the power consumption feature from the Maestro? This is the same thing as selling a product by being able to do something an then remove this feature without any advice or apologize...
![image](https://user-images.githubusercontent.com/35639060/51397924-47d3cb80-1b10-11e9-8ae7-db16812dd46c.png)

**Comment by stelpro** [comment]
Hi,

The power consumption is not removed from the Maestro. It's there.
The only thing is that SmartThings did not take advantage of that feature when they did their device handler implementation for the Maestro thermostat.
If the SmartThings hub would make the proper query to the thermostat, it would answer back.

**Comment by dantonino** [comment]
Hi @stelpro ,

I kind of agree with @vincentbarge in having an integrated House.

Can you please share how the query should looks like or some kind of the Document, therefore we can build a custom DeviceHandler to take advance of this feature?

@vincentbarge which tool you are using to build these graphs?

Thanks,
Diego

**Comment by stelpro** [comment]
Sure, if you want to customize your own device handler, you can certainly do that.
The consumed power can be fetched by reading the power consumption manufacturer specific attribute with the ID 0x4002 in the Thermostat Cluster 0x0201.

So you can either read this attribute or configure the thermostat to report it at the interval you desire.

The reported value will be the consumption in kWh since the beginning of the day

**Comment by vincentbarge** [comment]
Hi Diego,
I'm using Emoncms (from https://openenergymonitor.org/) to collect the data and to build the graphs. Webcore is to post the data in Emoncms. I do not code so webcore is a great tool for me, and it works perfectly since over a year.
My main issue now is to identify how much energy are taking my Stelpro that are part of the yellow gaps in the graph...

**Comment by vincentbarge** [comment]
Diego, Emoncms also have an app available for your phone. The app is pretty simple, but still usefull if you want to see your data without using a computeur. There is no such options to build 'complex' graphs, but still usefull when you want to momitor your consumption 'on the go'
